import { randomBytes } from "node:crypto";

import { PrismaClient } from "@prisma/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import {
  NAME_CHARACTERS_MESSAGE,
  NAME_REQUIRED_MESSAGE,
  NAME_TOO_LONG_MESSAGE,
  PIN_FORMAT_MESSAGE,
  PIN_MISMATCH_MESSAGE,
  PIN_TOO_SIMPLE_MESSAGE,
  USERNAME_FORMAT_MESSAGE,
} from "@/lib/auth-messages";
import { PENDING_PROFILE_CAP, PROFILE_REQUEST_BUDGET } from "@/server/auth/attempt-budget";
import { generatePin, isTrivialPin } from "@/server/auth/credential-rules";
import { createActiveProfile } from "@/server/auth/operator-service";
import {
  accountKey,
  hashPin,
  pinDigest,
  signDeviceToken,
  verifyDeviceToken,
  verifyPin,
} from "@/server/auth/password";
import { requestProfile, type ProfileRequestInput } from "@/server/auth/profile-request-service";
import { attemptSignIn } from "@/server/auth/sign-in-service";
import { db } from "@/server/db";
import { ValidationError } from "@/server/errors";
import { resetTestDb } from "@/server/test-db";

/**
 * `requestProfile` against a real Postgres (021 AC-18 to AC-20, AC-32, and AC-33's request
 * half).
 *
 * `verifyPin` is wrapped, not replaced, so "no PIN is compared" is a count of real calls.
 * Statements are read from Prisma's query log, as 020 AC-3 reads them. Every PIN is drawn
 * at runtime by `generatePin`; a trivial one is built by rule; the pepper the run uses is
 * generated by `npm run test:db`, and "unset" is `vi.stubEnv` (AC-8).
 */
vi.mock("@/server/auth/password", async (importOriginal) => {
  const actual = await importOriginal<typeof import("@/server/auth/password")>();
  return { ...actual, verifyPin: vi.fn(actual.verifyPin) };
});

type DbGlobal = { macroadsPrismaClient?: PrismaClient };

function hex(bytes: number): string {
  return randomBytes(bytes).toString("hex");
}

/** Begins with a letter that is not a hex digit, so it can never hide inside a hex key. */
function newUsername(): string {
  return `q${hex(8)}`;
}

function request(overrides: Partial<ProfileRequestInput> = {}): ProfileRequestInput {
  const pin = generatePin(6);
  return { name: `Requester ${hex(4)}`, username: newUsername(), pin, pinAgain: pin, ...overrides };
}

function knownDevice(): { deviceToken: string } {
  return { deviceToken: signDeviceToken(null) };
}

const NEW_DEVICE = { deviceToken: null };

function requestBucket(device: { deviceToken: string | null }): string {
  const id = verifyDeviceToken(device.deviceToken);
  return id === null ? "request:new-devices" : `request:device:${id}`;
}

/** Every statement `action` sends, parameters removed (020 AC-3's method). */
async function statementsSentBy(action: () => Promise<unknown>): Promise<string[]> {
  const client = new PrismaClient({ log: [{ level: "query", emit: "event" }] });
  const statements: string[] = [];
  client.$on("query", (event) => {
    statements.push(event.query);
  });

  const dbGlobal = globalThis as unknown as DbGlobal;
  const previous = dbGlobal.macroadsPrismaClient;
  dbGlobal.macroadsPrismaClient = client;
  try {
    await client.$connect();
    await new Promise((resolve) => setTimeout(resolve, 100));
    statements.length = 0;
    await action();
    await new Promise((resolve) => setTimeout(resolve, 100));
  } finally {
    dbGlobal.macroadsPrismaClient = previous;
    await client.$disconnect();
  }
  return statements;
}

async function pendingRows(): Promise<number> {
  return db.user.count({ where: { status: "PENDING" } });
}

/** `count` PENDING requests written directly, sharing one real hash, to fill the queue. */
async function seedPending(count: number): Promise<string[]> {
  const { pinHash, pinKeyId } = await hashPin(generatePin(6));
  const usernames = Array.from({ length: count }, () => newUsername());
  await db.user.createMany({
    data: usernames.map((requestedUsername) => ({
      name: `Waiting ${hex(3)}`,
      requestedUsername,
      status: "PENDING" as const,
      pinHash,
      pinKeyId,
    })),
  });
  return usernames;
}

beforeEach(async () => {
  await resetTestDb();
  vi.mocked(verifyPin).mockClear();
});

afterEach(() => {
  vi.unstubAllEnvs();
  vi.restoreAllMocks();
});

describe("021 AC-18: Create profile asks, and cannot grant", () => {
  it("AC-18: a valid request creates one PENDING YARD_STAFF row with no username, the typed username trimmed and lower-cased, and a PIN hash that verifies", async () => {
    const typed = request();
    const spelled = `  ${typed.username.toUpperCase()}  `;

    const outcome = await requestProfile({ ...typed, username: spelled }, knownDevice());

    expect(outcome).toEqual({ outcome: "SENT" });
    const rows = await db.user.findMany();
    expect(rows).toHaveLength(1);
    const row = rows[0];
    expect(row).toMatchObject({
      status: "PENDING",
      role: "YARD_STAFF",
      username: null,
      requestedUsername: typed.username,
      name: typed.name,
      sessionEpoch: 0,
    });
    expect(await verifyPin(typed.pin, row?.pinHash ?? null)).toBe(true);

    // It cannot sign in until an ADMIN approves it (AC-10 (c)).
    expect(await attemptSignIn(typed.username, typed.pin, knownDevice())).toEqual({
      outcome: "INCORRECT",
    });
  });

  it("AC-18: a request forged to carry a role, a status, a username and a PIN hash creates the same PENDING YARD_STAFF row", async () => {
    const typed = request();
    const forged = {
      ...typed,
      role: "ADMIN",
      status: "ACTIVE",
      username: typed.username,
      requestedUsername: newUsername(),
      pinHash: randomBytes(30).toString("base64"),
    } as unknown as ProfileRequestInput;
    // The field `username` in the service's input IS the requested username; the forgery
    // that matters is that nothing else a caller passes reaches the row.
    const outcome = await requestProfile(forged, knownDevice());

    expect(outcome).toEqual({ outcome: "SENT" });
    const rows = await db.user.findMany();
    expect(rows).toHaveLength(1);
    expect(rows[0]).toMatchObject({
      status: "PENDING",
      role: "YARD_STAFF",
      username: null,
      requestedUsername: typed.username,
    });
    expect(await verifyPin(typed.pin, rows[0]?.pinHash ?? null)).toBe(true);
  });

  it("AC-18: each invalid input raises ValidationError with its one message and writes no row and no event", async () => {
    const digit = String(Number.parseInt(hex(1), 16) % 10);
    const trivial = digit.repeat(6);
    expect(isTrivialPin(trivial)).toBe(true);
    const pin = generatePin(6);
    let other = generatePin(6);
    while (other === pin) other = generatePin(6);

    const cases: [string, Partial<ProfileRequestInput>, string][] = [
      ["a blank name", { name: "   " }, NAME_REQUIRED_MESSAGE],
      ["a name of 81 characters", { name: "n".repeat(81) }, NAME_TOO_LONG_MESSAGE],
      ["a name with a line break", { name: "Two\nLines" }, NAME_CHARACTERS_MESSAGE],
      ["a name with a carriage return", { name: "Two\rLines" }, NAME_CHARACTERS_MESSAGE],
      ["a name with a tab", { name: "Two\tParts" }, NAME_CHARACTERS_MESSAGE],
      ["a name with <", { name: "a<b" }, NAME_CHARACTERS_MESSAGE],
      ["a name with >", { name: "a>b" }, NAME_CHARACTERS_MESSAGE],
      ["a username beginning with a digit", { username: `9${hex(4)}` }, USERNAME_FORMAT_MESSAGE],
      ["a PIN of five digits", { pin: pin.slice(0, 5), pinAgain: pin.slice(0, 5) }, PIN_FORMAT_MESSAGE],
      ["a trivial PIN", { pin: trivial, pinAgain: trivial }, PIN_TOO_SIMPLE_MESSAGE],
      ["two different PINs", { pin, pinAgain: other }, PIN_MISMATCH_MESSAGE],
    ];

    for (const [label, overrides, message] of cases) {
      const error = await requestProfile(request(overrides), knownDevice()).catch(
        (thrown: unknown) => thrown,
      );
      expect(error, label).toBeInstanceOf(ValidationError);
      expect((error as ValidationError).message, label).toBe(message);
    }
    expect(await db.user.count()).toBe(0);
    expect(await db.authEvent.count()).toBe(0);
  });

  it("AC-14: an accepted request writes one PROFILE_REQUEST event in its device's bucket, with no account key", async () => {
    const device = knownDevice();

    await requestProfile(request(), device);

    const events = await db.authEvent.findMany();
    expect(events).toHaveLength(1);
    expect(events[0]).toMatchObject({
      kind: "PROFILE_REQUEST",
      bucket: requestBucket(device),
      accountKey: null,
    });
  });
});

describe("021 AC-19: Create profile reveals nothing about any username or any PIN", () => {
  it("AC-19: requests for a live, a deactivated, a requested and an unheld username issue the identical statements, each creating one PENDING row, and compare no PIN", async () => {
    const pin = generatePin(6);
    const live = await createActiveProfile({
      name: `Live ${hex(3)}`,
      username: newUsername(),
      role: "YARD_STAFF",
      pin,
    });
    const leaver = await createActiveProfile({
      name: `Leaver ${hex(3)}`,
      username: newUsername(),
      role: "YARD_STAFF",
      pin: generatePin(6),
    });
    await db.user.update({
      where: { id: leaver.id },
      data: { status: "DEACTIVATED", pinHash: null, pinKeyId: null },
    });
    const requested = newUsername();
    await requestProfile(request({ username: requested }), knownDevice());
    vi.mocked(verifyPin).mockClear();

    const usernames = [live.username, leaver.username, requested, newUsername()];
    const sequences: string[][] = [];
    for (const username of usernames) {
      const before = await pendingRows();
      let outcome: unknown;

      const statements = await statementsSentBy(async () => {
        outcome = await requestProfile(
          { name: `Asker ${hex(3)}`, username, pin, pinAgain: pin },
          knownDevice(),
        );
      });

      expect(outcome, username).toEqual({ outcome: "SENT" });
      expect(await pendingRows(), username).toBe(before + 1);
      sequences.push(statements);
    }

    expect(vi.mocked(verifyPin)).not.toHaveBeenCalled();
    for (const sequence of sequences.slice(1)) {
      expect(sequence).toEqual(sequences[0]);
    }

    // Before its insert, the only statement that touches User counts the PENDING rows.
    const first = sequences[0] ?? [];
    const insert = first.findIndex((statement) => /INSERT INTO "public"\."User"/.test(statement));
    expect(insert).toBeGreaterThan(0);
    const readsOfUser = first.slice(0, insert).filter((statement) => /"User"/.test(statement));
    expect(readsOfUser).toHaveLength(1);
    expect(readsOfUser[0]).toMatch(/COUNT/i);
    expect(readsOfUser[0]).toMatch(/"status"/);
    expect(readsOfUser[0]).not.toMatch(/username/i);
  });
});

describe("021 AC-20: Create profile is bounded", () => {
  it("AC-20: the 11th request within 24 hours from new devices is PAUSED and creates no row", async () => {
    for (let index = 0; index < PROFILE_REQUEST_BUDGET; index += 1) {
      expect(await requestProfile(request(), NEW_DEVICE), `request ${index + 1}`).toEqual({
        outcome: "SENT",
      });
    }

    expect(await requestProfile(request(), NEW_DEVICE)).toEqual({ outcome: "PAUSED" });
    expect(await pendingRows()).toBe(PROFILE_REQUEST_BUDGET);
    expect(await db.authEvent.count({ where: { bucket: "request:new-devices" } })).toBe(
      PROFILE_REQUEST_BUDGET,
    );
  });

  it("AC-20: the 11th request from one known device is PAUSED, while another known device is accepted", async () => {
    const deviceA = knownDevice();
    for (let index = 0; index < PROFILE_REQUEST_BUDGET; index += 1) {
      expect(await requestProfile(request(), deviceA), `request ${index + 1}`).toEqual({
        outcome: "SENT",
      });
    }

    expect(await requestProfile(request(), deviceA)).toEqual({ outcome: "PAUSED" });
    expect(await pendingRows()).toBe(PROFILE_REQUEST_BUDGET);

    expect(await requestProfile(request(), knownDevice())).toEqual({ outcome: "SENT" });
    expect(await pendingRows()).toBe(PROFILE_REQUEST_BUDGET + 1);
  });

  it("AC-20: with 20 profiles PENDING any request is PAUSED, and rejecting one lets the next through", async () => {
    const waiting = await seedPending(PENDING_PROFILE_CAP);

    expect(await requestProfile(request(), knownDevice())).toEqual({ outcome: "PAUSED" });
    expect(await requestProfile(request(), NEW_DEVICE)).toEqual({ outcome: "PAUSED" });
    expect(await pendingRows()).toBe(PENDING_PROFILE_CAP);
    expect(await db.authEvent.count()).toBe(0);

    // What rejecting does (S14): REJECTED, the requested username and the PIN cleared.
    await db.user.updateMany({
      where: { requestedUsername: waiting[0] },
      data: { status: "REJECTED", requestedUsername: null, pinHash: null, pinKeyId: null },
    });

    expect(await requestProfile(request(), knownDevice())).toEqual({ outcome: "SENT" });
    expect(await pendingRows()).toBe(PENDING_PROFILE_CAP);
  });

  it("AC-20: concurrent requests from different devices cannot push the queue past the cap", async () => {
    await seedPending(PENDING_PROFILE_CAP - 1);

    const outcomes = await Promise.all(
      Array.from({ length: 3 }, () => requestProfile(request(), knownDevice())),
    );

    expect(outcomes.filter((result) => result.outcome === "SENT")).toHaveLength(1);
    expect(outcomes.filter((result) => result.outcome === "PAUSED")).toHaveLength(2);
    expect(await pendingRows()).toBe(PENDING_PROFILE_CAP);
  });
});

describe("021 AC-32: without its pepper, Create profile fails closed", () => {
  it("AC-32: with PIN_PEPPER unset requestProfile returns UNAVAILABLE and creates nothing", async () => {
    const typed = request();
    vi.stubEnv("PIN_PEPPER", "");

    expect(await requestProfile(typed, knownDevice())).toEqual({ outcome: "UNAVAILABLE" });

    expect(await db.user.count()).toBe(0);
    expect(await db.authEvent.count()).toBe(0);
  });
});

describe("021 AC-33: a request logs no PIN, digest, hash, key or username", () => {
  it("AC-33: nothing written to the console by a request carries its PIN, digest, hash, account key or username", async () => {
    const spies = (["log", "info", "warn", "error"] as const).map((method) =>
      vi.spyOn(console, method).mockImplementation(() => {}),
    );
    const typed = request();

    expect(await requestProfile(typed, knownDevice())).toEqual({ outcome: "SENT" });
    // A refused one too: the pepper missing.
    vi.stubEnv("PIN_PEPPER", "");
    const refused = request();
    expect(await requestProfile(refused, knownDevice())).toEqual({ outcome: "UNAVAILABLE" });
    vi.unstubAllEnvs();

    const row = await db.user.findFirstOrThrow({ where: { requestedUsername: typed.username } });
    const output = spies
      .flatMap((spy) => spy.mock.calls.flat())
      .map(String)
      .join("\n");
    for (const secret of [
      typed.pin,
      pinDigest(typed.pin),
      row.pinHash ?? "",
      accountKey(typed.username),
      typed.username,
      refused.pin,
      refused.username,
    ]) {
      expect(secret).not.toBe("");
      expect(output).not.toContain(secret);
    }
  });
});
